import { useState,useEffect } from 'react';
import API from '../api';
export default function MyPredictions({competitionId,tournamentId,userId,onNavigate}) {
 const [data,setData]=useState(null),[summary,setSummary]=useState(null),[filter,setFilter]=useState('Tous'),[error,setError]=useState(''),[revision,setRevision]=useState(0),[progress,setProgress]=useState(null);
 useEffect(()=>{const controller=new AbortController();Promise.all([API.get(`/me/predictions?competitionId=${competitionId}`,{signal:controller.signal}),API.get(`/me/summary/${tournamentId}`,{signal:controller.signal})]).then(([a,b])=>{if(controller.signal.aborted)return;setData(a.data);setSummary(b.data);setError('');
 const key=`rank:${userId}:${tournamentId}`;try{const old=JSON.parse(localStorage.getItem(key)||'null');const rank=b.data.ranking?.rank;setProgress(old&&rank?{change:old.rank-rank,date:old.date}:null);if(rank)localStorage.setItem(key,JSON.stringify({rank,date:new Date().toISOString()}));}catch{/* Storage may be disabled. */}
 }).catch(e=>{if(!controller.signal.aborted)setError(e.response?.data?.error||'Chargement impossible. Réessayez.');});return()=>controller.abort();},[competitionId,tournamentId,userId,revision]);
 const rows=data?.rows||[],saved=rows.filter(r=>r.prediction).length;
 return <section className="feature-panel"><div className="feature-heading"><h2>Mes pronostics</h2><button onClick={()=>setRevision(n=>n+1)}>Actualiser l’affichage</button></div>
 <p className="muted">Les données affichées sont celles du dernier import officiel. Ce bouton ne lance pas de collecte sur FencingTimeLive.</p>
 {error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Chargement…</p>}
 {data&&<><h3>{data.competition.name}</h3><p><strong>{saved} / {rows.length}</strong> pronostics enregistrés · {rows.filter(r=>r.status==='À compléter').length} encore à compléter</p><progress value={saved} max={rows.length||1} aria-label="Pronostics enregistrés"/>
 <div className="filter-row">{['Tous','À compléter','Enregistré','Clos','Terminé'].map(s=><button key={s} aria-pressed={filter===s} onClick={()=>setFilter(s)}>{s}</button>)}</div>
 {rows.filter(r=>filter==='Tous'||r.status===filter).map(r=><article className="prediction-summary" key={r.key}><div className="feature-heading"><strong>{r.name}</strong><span className="status-pill">{r.status}</span></div><small>{r.type}{r.round&&` · ${r.round}`}</small><p>Mon pronostic : {r.prediction||'Non renseigné'}</p>{r.result&&<p>Résultat : {r.result}</p>}{r.points!==null&&<p><strong>{r.points} points</strong> · {r.details.join(' · ')}</p>}{r.sourceCheckedAt&&<small>Vérification officielle : {new Date(r.sourceCheckedAt).toLocaleString('fr-FR')}</small>}<div><button className="button-secondary" onClick={()=>onNavigate(r.type==='Poule'?'pools':'play',r.key)}>Voir {r.type==='Poule'?'la poule':r.type==='Podium'?'le podium':'le match'}</button></div></article>)}</>}
 {summary&&<aside className="feature-panel"><h3>Mon bilan du tournoi</h3><div className="stat-grid"><p><strong>{summary.ranking?.rank||'—'}</strong> / {summary.players} au classement</p><p><strong>{summary.ranking?.totalPoints||0}</strong> points</p><p><strong>{summary.exact}</strong> scores exacts</p><p><strong>{summary.winners} / {summary.played}</strong> bons vainqueurs ({summary.accuracy??0} %)</p></div><p>{progress?`Évolution depuis la consultation du ${new Date(progress.date).toLocaleString('fr-FR')} : ${progress.change>0?'+':''}${progress.change} place(s).`:'L’évolution de votre rang sera comparée lors de votre prochaine consultation.'}</p><small>Le taux de réussite porte sur vos pronostics de matchs terminés. Les ex æquo partagent le même rang.</small></aside>}
 </section>;
}
